### ISSUE TITLE
Question re: third phase

### ISSUE THREAD

**Issue by Jestre** [michaeladams/obsidian-text-progress-bar#11]
Not really an issue, but more of a question.  Is there a way to represent an intermediate phase in a full-length series, e.g. I am reading a 10 book series, and I'd like all 10 to be displayed, and I have the ones read marked with a green book, the ones unread with a red book, but I'm wondering if there is a way to display an open book emoji for the one I am reading?

I think I understand the use of the transition icon when used in a shorter representation than the actual number of items, but I don't believe that would apply here.

Thanks!

**Comment by michaeladams** [comment]
Correct, the transition icon is for representing partial values.

Possibly options, maybe I add in support for decimal values, which would trigger the transition icon.  (Eg, I've read 5.5 books)  Although that sounds odd for books read, that way you can display the open book icon when you start reading.

Or/And a new 'active' option for an icon that represents the border between filled and empty, but that would be always on, and may not represent the fact your finished 5 books in the series but haven't actually started the 6th.

**Comment by Jestre** [comment]
Either would work, though my preference would be for the first.  I regularly track my reading progress on Bookwyrm or GoodReads, which represents the progress as a percentage, so the 5.5 would be very similar.

Thank you for thinking about it.
